runtime: python
env: flex
# entrypoint: gunicorn -b:$PORT welcome:app
# entrypoint: flask run
runtime_config:
  python_version: 3

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
